import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'

test('login, server registration, ingest, search, session details, token revocation and mobile',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('관리자 계정').fill('admin')
 await page.getByLabel('비밀번호',{exact:true}).fill(readFileSync('/run/test-password','utf8').trim())
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await expect(page.getByRole('heading',{name:'전체 현황'})).toBeVisible()
 await page.getByRole('button',{name:'서버 관리',exact:true}).click()
 const name='browser-fixture-'+Date.now()
 await page.getByLabel('서버 이름',{exact:true}).fill(name)
 await page.getByRole('button',{name:'서버 등록',exact:true}).click()
 const token=await page.getByLabel('발급 토큰').inputValue()
 expect(token).toHaveLength(48)
 const now=Date.now()
 const res=await request.post('/api/ingest',{headers:{Authorization:'Bearer '+token},data:{events:[{id:'start',time:now,kind:'session_start',session_id:'fixture:10',user:'alice',ip:'203.0.113.10',args:[]},{id:'exec',time:now+1,kind:'exec',session_id:'fixture:10',user:'alice',effective_user:'root',program:'/usr/bin/id',args:['id','--token=secret'],outcome:'yes'}],health:'ok',backlog:0,dropped:0,active_sessions:['fixture:10']}})
 expect(res.status()).toBe(200)
 await page.getByRole('button',{name:'닫기',exact:true}).click()
 await page.getByRole('button',{name:'활동 기록',exact:true}).click()
 await page.getByLabel('명령 검색',{exact:true}).fill('id')
 await expect(page.locator('tr').filter({hasText:name}).locator('code').filter({hasText:'id --token=[REDACTED]'})).toBeVisible()
 await expect(page.locator('tbody')).not.toContainText('--token=secret')
 await page.getByRole('button',{name:'접속 세션',exact:true}).click()
 const sessionRow=page.locator('tr').filter({hasText:name})
 await sessionRow.getByRole('button',{name:'상세 보기'}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.getByRole('dialog').locator('code').filter({hasText:'id --token=[REDACTED]'})).toBeVisible()
 await page.getByRole('button',{name:'닫기 ✕'}).click()
 await page.getByRole('button',{name:'서버 관리',exact:true}).click()
 page.once('dialog',dialog=>dialog.accept())
 await page.locator('tr').filter({hasText:name}).getByRole('button',{name:'폐기',exact:true}).click()
 await expect(page.locator('tr').filter({hasText:name})).toHaveCount(0)
 await page.reload()
 await page.getByRole('button',{name:'서버 관리',exact:true}).click()
 await expect(page.locator('tr').filter({hasText:name})).toHaveCount(0)
 await page.getByRole('button',{name:'활동 기록',exact:true}).click()
 await expect(page.locator('tr').filter({hasText:name})).toHaveCount(0)
 await expect(page.getByLabel('서버',{exact:true}).locator('option').filter({hasText:name})).toHaveCount(0)
 await page.getByRole('button',{name:'접속 세션',exact:true}).click()
 await expect(page.locator('tr').filter({hasText:name})).toHaveCount(0)
 const denied=await request.post('/api/ingest',{headers:{Authorization:'Bearer '+token},data:{events:[],health:'ok',backlog:0,dropped:0,active_sessions:[]}})
 expect(denied.status()).toBe(401)
 await page.getByRole('button',{name:'전체 현황',exact:true}).click()
 await page.setViewportSize({width:390,height:844})
 await expect(page.getByRole('heading',{name:'전체 현황'})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.screenshot({path:'/tmp/sshlogger-browser-results/mobile.png',fullPage:true})
 await page.setViewportSize({width:1440,height:1000})
 await page.screenshot({path:'/tmp/sshlogger-browser-results/dashboard.png',fullPage:true})
 await page.getByRole('button',{name:'로그아웃'}).click()
 await expect(page.getByRole('button',{name:'대시보드 로그인'})).toBeVisible()
 expect(errors).toEqual([])
})

test('important view filters before pagination, exposes hidden records, and collapses long scripts', async({page,request})=>{
 await page.goto('/')
 await page.getByLabel('관리자 계정').fill('admin')
 await page.getByLabel('비밀번호',{exact:true}).fill(readFileSync('/run/test-password','utf8').trim())
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await page.getByRole('button',{name:'서버 관리',exact:true}).click()
 const name='noise-fixture-'+Date.now()
 await page.getByLabel('서버 이름',{exact:true}).fill(name)
 await page.getByRole('button',{name:'서버 등록',exact:true}).click()
 const token=await page.getByLabel('발급 토큰').inputValue()
 const now=Date.now()-10000
 const common={kind:'exec',session_id:'noise:1',user:'alice',effective_user:'alice',outcome:'yes'}
 const script='printf "begin"\n'+Array.from({length:20},(_,i)=>`printf "line ${i}"`).join('\n')
 const events=[
  {...common,id:'start',kind:'session_start',time:now,program:'/usr/sbin/sshd',args:[],ip:'203.0.113.44'},
  {...common,id:'read',time:now+1,pid:54321,ppid:12345,program:'/usr/bin/cat',args:['cat','/etc/ssh/sshd_config']},
  {...common,id:'failed',time:now+2,program:'/usr/bin/getconf',args:['getconf','LONG_BIT'],outcome:'no'},
  {...common,id:'elevated',time:now+3,program:'/usr/bin/getconf',args:['getconf','LONG_BIT'],effective_user:'root'},
  {...common,id:'script',time:now+4,program:'/bin/bash',args:['bash','-lc',script]},
  ...Array.from({length:120},(_,i)=>({...common,id:'routine-'+i,time:now+10+i,program:i%2?'/usr/bin/tr':'/usr/bin/getconf',args:i%2?['tr','[:upper:]','[:lower:]']:['getconf','LONG_BIT']})),
 ]
 expect((await request.post('/api/ingest',{headers:{Authorization:'Bearer '+token},data:{events,health:'ok',backlog:0,dropped:0,active_sessions:['noise:1']}})).status()).toBe(200)
 await page.getByRole('button',{name:'닫기',exact:true}).click()
 await page.getByRole('button',{name:'활동 기록',exact:true}).click()
 await page.getByLabel('서버',{exact:true}).selectOption({label:name})
 await expect(page.getByRole('button',{name:'주요 활동',exact:true})).toHaveAttribute('aria-pressed','true')
 await expect(page.locator('.activity-summary')).toContainText('보조 실행 120건')
 await expect(page.locator('.activity-count')).toHaveText('5건 표시 대상 / 전체 125건')
 await expect(page.locator('code').filter({hasText:'cat /etc/ssh/sshd_config'})).toBeVisible()
 await expect(page.locator('tr').filter({hasText:'cat /etc/ssh/sshd_config'}).locator('.process-ids')).toContainText('PID 54321')
 await expect(page.locator('tr').filter({hasText:'cat /etc/ssh/sshd_config'}).locator('.process-ids')).toContainText('부모 PID 12345')
 await expect(page.locator('code').filter({hasText:'tr [:upper:] [:lower:]'})).toHaveCount(0)
 await expect(page.getByText('실행 요청 실패',{exact:true})).toBeVisible()
 await page.getByText('전체 명령 펼치기',{exact:true}).click()
 await expect(page.locator('.command-details pre')).toContainText('line 19')
 await page.getByRole('button',{name:'전체 기록',exact:true}).click()
 await expect(page.locator('.activity-count')).toHaveText('125건 표시 대상 / 전체 125건')
 await expect(page.locator('code').filter({hasText:'tr [:upper:] [:lower:]'}).first()).toBeVisible()
 await expect(page.locator('.routine-reason').first()).toBeVisible()
 await page.getByLabel('명령 검색',{exact:true}).fill('tr ')
 await page.getByRole('button',{name:'주요 활동',exact:true}).click()
 await expect(page.locator('.activity-summary')).toContainText('보조 실행 60건')
 await expect(page.locator('tbody tr')).toHaveCount(0)
 await page.getByRole('button',{name:'보조 실행',exact:true}).click()
 await expect(page.locator('code').filter({hasText:'tr [:upper:] [:lower:]'}).first()).toBeVisible()
 await page.getByRole('button',{name:'접속 세션',exact:true}).click()
 await page.locator('tr').filter({hasText:name}).getByRole('button',{name:'상세 보기'}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.locator('.activity-count')).toHaveText('5건 표시 대상 / 전체 125건')
 await expect(dialog.locator('code').filter({hasText:'tr [:upper:] [:lower:]'})).toHaveCount(0)
 await dialog.getByRole('button',{name:'보조 실행',exact:true}).click()
 await expect(dialog.locator('.activity-count')).toHaveText('120건 표시 대상 / 전체 125건')
 await expect(dialog.locator('code').filter({hasText:'tr [:upper:] [:lower:]'}).first()).toBeVisible()
})

test('create administrator, change own password and sign in again', async ({page}) => {
 const errors:string[]=[]; page.on('pageerror', e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('관리자 계정',{exact:true}).fill('admin')
 await page.getByLabel('비밀번호',{exact:true}).fill(readFileSync('/run/test-password','utf8').trim())
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await page.getByRole('button',{name:'관리자 계정',exact:true}).click()
 const username='operator-'+Date.now()
 const password='initial-password-123'
 const changed='changed-password-456'
 await page.getByLabel('새 관리자 계정',{exact:true}).fill(username)
 await page.getByLabel('초기 비밀번호',{exact:true}).fill(password)
 await page.getByLabel('초기 비밀번호 확인',{exact:true}).fill(password)
 await page.getByRole('button',{name:'관리자 생성',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('관리자 계정을 생성했습니다.')
 await expect(page.getByRole('cell',{name:username,exact:true})).toBeVisible()
 await page.getByRole('button',{name:'로그아웃'}).click()
 await page.getByLabel('관리자 계정',{exact:true}).fill(username)
 await page.getByLabel('비밀번호',{exact:true}).fill(password)
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await page.getByRole('button',{name:'관리자 계정',exact:true}).click()
 await expect(page.getByText(username,{exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'관리자 계정 생성',exact:true})).toHaveCount(0)
 await page.reload()
 await expect(page.getByRole('heading',{name:'전체 현황',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'관리자 계정',exact:true}).click()
 await expect(page.getByText(username,{exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'관리자 계정 생성',exact:true})).toHaveCount(0)
 await page.setViewportSize({width:390,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 await page.getByLabel('현재 비밀번호',{exact:true}).fill('wrong-password')
 await page.getByLabel('새 비밀번호',{exact:true}).fill(changed)
 await page.getByLabel('새 비밀번호 확인',{exact:true}).fill(changed)
 await page.getByRole('button',{name:'비밀번호 변경',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('현재 비밀번호가 올바르지 않습니다.')
 await page.getByLabel('현재 비밀번호',{exact:true}).fill(password)
 await page.getByRole('button',{name:'비밀번호 변경',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('새 비밀번호로 다시 로그인하세요.')
 await page.getByLabel('비밀번호',{exact:true}).fill(password)
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await expect(page.getByRole('alert')).toContainText('계정 또는 비밀번호가 올바르지 않습니다.')
 await page.getByLabel('비밀번호',{exact:true}).fill(changed)
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await expect(page.getByRole('heading',{name:'관리자 계정',exact:true})).toBeVisible()
 expect(errors).toEqual([])
})

test('session termination confirms, queues, and displays agent result',async({page,request})=>{
 await page.goto('/')
 await page.getByLabel('관리자 계정').fill('admin')
 await page.getByLabel('비밀번호',{exact:true}).fill(readFileSync('/run/test-password','utf8').trim())
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await page.getByRole('button',{name:'서버 관리',exact:true}).click()
 const name='termination-fixture-'+Date.now()
 await page.getByLabel('서버 이름',{exact:true}).fill(name)
 await page.getByRole('button',{name:'서버 등록',exact:true}).click()
 const token=await page.getByLabel('발급 토큰').inputValue()
 const batch={can_terminate:true,health:'ok',backlog:0,dropped:0,active_sessions:['fixture:77'],events:[{id:'start',time:Date.now(),kind:'session_start',session_id:'fixture:77',user:'alice',ip:'203.0.113.77',args:[]}]}
 const ingest=(data:unknown)=>request.post('/api/ingest',{headers:{Authorization:'Bearer '+token},data})
 expect((await ingest(batch)).status()).toBe(200)
 await page.getByRole('button',{name:'닫기',exact:true}).click()
 await page.getByRole('button',{name:'접속 세션',exact:true}).click()
 const row=page.locator('tr').filter({hasText:name})
 page.once('dialog',d=>d.dismiss())
 await row.getByRole('button',{name:'강제 종료',exact:true}).click()
 expect((await (await ingest(batch)).json()).terminations).toBeUndefined()
 page.once('dialog',async d=>{expect(d.message()).toContain('alice');await d.accept()})
 await row.getByRole('button',{name:'강제 종료',exact:true}).click()
 await expect(row.getByRole('button',{name:'종료 요청 중…'})).toBeDisabled()
 const response=await (await ingest(batch)).json()
 expect(response.terminations).toHaveLength(1)
 expect((await ingest({...batch,termination_results:[{id:response.terminations[0].id,error:''}]})).status()).toBe(200)
 await expect(row.getByText('강제 종료 완료',{exact:true})).toBeVisible({timeout:10000})
 await expect(row.getByRole('button',{name:'강제 종료',exact:true})).toHaveCount(0)
})

test('super admin assigns servers and operator manages only assigned firewall',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('관리자 계정',{exact:true}).fill('admin')
 await page.getByLabel('비밀번호',{exact:true}).fill(readFileSync('/run/test-password','utf8').trim())
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await expect(page.getByRole('heading',{name:'전체 현황',exact:true})).toBeVisible()
 const me=await page.evaluate(async()=>await (await fetch('/api/me')).json())
 const post=async(path:string,data:unknown)=>page.evaluate(async({path,data,csrf})=>{const r=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});return await r.json()},{path,data,csrf:me.csrf})
 const name='firewall-'+Date.now(),hiddenName='hidden-'+Date.now()
 const server=await post('/servers',{name}),hidden=await post('/servers',{name:hiddenName})
 const ingest=async(result?:unknown)=>{const r=await request.post('/api/ingest',{headers:{Authorization:'Bearer '+server.token},data:{can_firewall:true,health:'ok',events:[],firewall_result:result}});expect(r.status()).toBe(200);return await r.json()}
 await ingest()
 const username='scoped-'+Date.now(),password='operator-password-123'
 await page.getByRole('button',{name:'관리자 계정',exact:true}).click()
 await page.getByLabel('새 관리자 계정',{exact:true}).fill(username)
 await page.getByLabel('초기 비밀번호',{exact:true}).fill(password)
 await page.getByLabel('초기 비밀번호 확인',{exact:true}).fill(password)
 await page.getByRole('button',{name:'관리자 생성',exact:true}).click()
 const account=page.locator('tr').filter({has:page.getByRole('cell',{name:username,exact:true})})
 await account.getByLabel(name,{exact:true}).check()
 page.once('dialog',d=>d.accept())
 await account.getByRole('button',{name:'권한 저장',exact:true}).click()
 await expect(account.getByRole('status')).toHaveText('저장했습니다.')
 await page.getByRole('button',{name:'IP 차단',exact:true}).click()
 await page.getByLabel('대상 서버',{exact:true}).selectOption(server.id)
 await page.getByLabel('SSH 포트 (쉼표로 구분)',{exact:true}).fill('22, 2222')
 await page.getByLabel('보호할 관리 IP (줄바꿈 또는 쉼표로 구분)',{exact:true}).fill('203.0.113.1')
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'방화벽 설정 저장',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('요청을 저장했습니다.')
 await page.getByRole('button',{name:'로그아웃'}).click()
 await page.getByLabel('관리자 계정',{exact:true}).fill(username)
 await page.getByLabel('비밀번호',{exact:true}).fill(password)
 await page.getByRole('button',{name:'대시보드 로그인'}).click()
 await expect(page.getByRole('button',{name:'서버 관리',exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'IP 차단',exact:true}).click()
 await expect(page.getByLabel('대상 서버',{exact:true}).locator('option')).toHaveCount(2)
 await expect(page.getByLabel('대상 서버',{exact:true}).locator('option')).not.toContainText([hiddenName])
 await page.getByLabel('대상 서버',{exact:true}).selectOption(server.id)
 await expect(page.getByRole('button',{name:'방화벽 설정 저장',exact:true})).toHaveCount(0)
 await page.getByLabel('차단할 IP',{exact:true}).fill('203.0.113.1')
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'IP 차단',exact:true}).last().click()
 await expect(page.getByRole('alert')).toContainText('보호 IP')
 await page.getByLabel('차단할 IP',{exact:true}).fill('2001:db8::10')
 await page.getByLabel('기존 SSH 연결도 차단',{exact:true}).check()
 page.once('dialog',d=>d.accept())
 await page.getByRole('button',{name:'IP 차단',exact:true}).last().click()
 await expect(page.getByRole('status')).toContainText('요청을 저장했습니다.')
 const policy=(await ingest()).firewall
 expect(policy.bans).toEqual([{ip:'2001:db8::10',disconnect:true}])
 expect(policy.ports).toEqual([22,2222])
 await ingest({revision:policy.revision,error:''})
 const ban=page.locator('tr').filter({has:page.getByRole('button',{name:'차단 해제',exact:true})})
 await expect(ban).toContainText('차단됨',{timeout:10000})
 page.once('dialog',d=>d.accept())
 await ban.getByRole('button',{name:'차단 해제',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('요청을 저장했습니다.')
 const unban=(await ingest()).firewall;expect(unban.bans).toEqual([])
 await ingest({revision:unban.revision,error:''})
 await expect(page.getByText('등록된 차단 IP가 없습니다.',{exact:true})).toBeVisible()
 const denied=await page.evaluate(async(id)=>{const r=await fetch(`/api/servers/${id}/firewall`);return r.status},hidden.id)
 expect(denied).toBe(404)
 await page.setViewportSize({width:390,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
 expect(errors).toEqual([])
})
