import { test, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';

const screenshots = '/tmp/sshlogger-ui-results';
test('management dialogs, keyboard navigation, draft preservation and responsive layout', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await page.getByLabel('관리자 계정', { exact: true }).fill('admin');
  await page.getByLabel('비밀번호', { exact: true }).fill(readFileSync(process.env.TEST_PASSWORD_FILE || '/run/test-password', 'utf8').trim());
  await page.getByRole('button', { name: '대시보드 로그인' }).click();
  await page.getByRole('heading', { name: '전체 현황', exact: true }).waitFor();
  const me = await (await page.request.get('/api/me')).json();
  const serverName = 'design-review-' + Date.now();
  const server = await (await page.request.post('/api/servers', { headers: { 'X-CSRF-Token': me.csrf, Origin: 'http://localhost:18080' }, data: { name: serverName } })).json();
  const ingest = async () => request.post('/api/ingest', { headers: { Authorization: 'Bearer ' + server.token }, data: { can_firewall: true, health: 'ok', events: [] } });
  await ingest();
  mkdirSync(screenshots, { recursive: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: '관리자 계정', exact: true }).click();
  await expect(page.getByRole('heading', { name: '등록된 관리자' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'admin 권한 편집', exact: true })).toBeVisible();
  await page.screenshot({ path: screenshots + '/accounts-desktop.png', fullPage: true, animations: 'disabled' });
  const add = page.getByRole('button', { name: '관리자 추가', exact: true });
  await add.click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await page.getByLabel('새 관리자 계정', { exact: true }).fill('validation-only');
  await page.getByLabel('초기 비밀번호', { exact: true }).fill('short');
  await page.getByLabel('초기 비밀번호 확인', { exact: true }).fill('different');
  await dialog.getByRole('button', { name: '관리자 생성', exact: true }).click();
  await expect(page.getByLabel('초기 비밀번호', { exact: true })).toBeFocused();
  await expect(dialog.getByRole('alert')).toHaveCount(2);
  await page.getByRole('button', { name: '초기 비밀번호 표시', exact: true }).click();
  await expect(page.getByLabel('초기 비밀번호', { exact: true })).toHaveAttribute('type', 'text');
  await page.screenshot({ path: screenshots + '/account-dialog.png', fullPage: true, animations: 'disabled' });
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(add).toBeFocused();
  await page.setViewportSize({ width: 375, height: 812 });
  await page.screenshot({ path: screenshots + '/accounts-mobile.png', fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '비밀번호 변경', exact: true }).click();
  await page.screenshot({ path: screenshots + '/password-mobile.png', fullPage: true, animations: 'disabled' });
  await page.keyboard.press('Escape');

  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'IP 차단', exact: true }).click();
  await expect(page.getByRole('heading', { name: '관리할 서버를 선택하세요.' })).toBeVisible();
  await page.getByLabel('대상 서버', { exact: true }).selectOption(server.id);
  await expect(page.getByRole('heading', { name: 'IP 차단 추가' })).toBeVisible();
  await page.screenshot({ path: screenshots + '/firewall-desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('tab', { name: '차단 목록' }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('tab', { name: '변경 이력', exact: true })).toBeFocused();
  await expect(page.getByRole('heading', { name: '아직 변경 이력이 없습니다.' })).toBeVisible();
  await expect(page.getByRole('button', { name: '다음', exact: true })).toHaveCount(0);
  await page.keyboard.press('ArrowRight');
  const ports = page.getByLabel('SSH 포트 (쉼표로 구분)', { exact: true });
  await ports.fill('22, 2222');
  let polls = 0;
  page.on('response', (response) => { if (response.url().includes(`/servers/${server.id}/firewall?`)) polls++; });
  await expect.poll(() => polls, { timeout: 10000 }).toBeGreaterThan(0);
  await expect(ports).toHaveValue('22, 2222');
  await page.getByRole('tab', { name: '차단 목록' }).click();
  await page.getByRole('tab', { name: '방화벽 설정', exact: true }).click();
  await expect(ports).toHaveValue('22, 2222');
  await page.screenshot({ path: screenshots + '/firewall-settings.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('tab', { name: '차단 목록' }).click();
  await page.getByLabel('차단할 IP', { exact: true }).fill('203.0.113.99');
  await page.getByRole('button', { name: 'IP 차단', exact: true }).last().click();
  await expect(dialog).toContainText(serverName);
  await expect(dialog).toContainText('203.0.113.99');
  await dialog.getByRole('button', { name: '취소', exact: true }).click();
  const policy = await (await page.request.get(`/api/servers/${server.id}/firewall`)).json();
  expect(policy.policy.bans).toEqual([]);
  await expect(page.getByLabel('차단할 IP', { exact: true })).toHaveValue('203.0.113.99');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  for (const viewport of [{ width: 375, height: 812 }, { width: 812, height: 375 }]) {
    await page.setViewportSize(viewport);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `${screenshots}/firewall-${viewport.width}.png`, fullPage: true, animations: 'disabled' });
  }
  expect(errors).toEqual([]);
});
